### ISSUE TITLE
Add deploy support for Junction 

### ISSUE THREAD

**Issue by Celldweller** [magento-hackathon/magento-composer-installer#11]
http://www.debianroot.de/windows/symlinks-unter-windows-xp-erstellen-1328.html

Junction is a symlink utility for Windows XP

**Comment by Flyingmana** [comment]
XP is not a supported system anymore, symlinking got better with new windows versions and things seem to evolve into a direction, which makes symlinks not needed anymore in the future.
So I close this Issue.
