### ISSUE TITLE
Newest version breaks on composer update

### ISSUE THREAD

**Issue by mpaepper** [magento-hackathon/magento-composer-installer#117]
PHP Fatal error:  Interface 'Composer\Plugin\PluginInterface' not found in /var/www/vhosts/domain.com/httpdocs/vendor/magento-hackathon/magento-composer-installer/src/MagentoHackathon/Composer/Magento/InstallerPlugin.php on line 10

The file InstallerPlugin is not in the repo?

**Comment by Flyingmana** [comment]
I close this issue.
The composer team recommends to do plugin/installer updates only together with --no-plugins/--no-custom-installers argument, so this issue is in the recommended way of usage not existent.
