### ISSUE TITLE
Configure deploy strategy in the package

### ISSUE THREAD

**Issue by Drecomm** [magento-hackathon/magento-composer-installer#127]
I would like to configure the deploy strategy for some packages in the package itself.
we use different deploy-strategies per package, almost in every project the same way.

would this be sufficient by itself, or should there be an extra configuration options, 
to specify that the packages configuration is used?

for example:
the root composer.json contains:

```json
{
    ...
    "extra":{
        "magento-root-dir": "htdocs/",
        "magento-deploystrategy": "symlink"
    }
    ...
}
```

one of the included packages contains:

```json
{
    ...
    "extra":{
        "magento-deploystrategy": "copy"
    }
    ...
}
```

**Comment by Flyingmana** [comment]
I decide with the following reasons against this Feature:

* not every magento related installer supports the same deploy strategys
* deploy strategys can differ between major versions of the installer
* its a violation of concerns
* the composer team sets an example with not supporting the same for scripts and repository definitions
* it should only be needed in exceptional cases to use a non global deploy strategy
