### ISSUE TITLE
"Package Abandoned" error message

### ISSUE THREAD

**Issue by fmarangi** [magento-hackathon/magento-composer-installer#144]
When trying to install the Composer Installer via `packagist`, composer outputs the following error message:

    Package magento-hackathon/magento-composer-installer is abandoned, you should avoid using it. No replacement was suggested.

If you specify `http://packages.firegento.com` under `repositories` no error message is displayed.

**Comment by oviliz** [comment]
Hi @fmarangi Francesco. Hod did you managed to add http://packages.firegento.com to the repositories?

**Comment by Flyingmana** [comment]
```composer.phar config -g repositories.firegento composer http://packages.firegento.com``` adds the repository globally, so you dont need to add this for every project

**Comment by oviliz** [comment]
Thank you. I've done that but nothing seems changed.

I've tried to add this into the composer.json but still the installer abandoned message. I believe I'm doing something wrong.
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.firegento.com"
        }
    ],

**Comment by davidverholen** [comment]
did you add the repository to your root composer.json?
Repositories are only read from there

**Comment by oviliz** [comment]
Yes David, the composer.json is on the root while the composer.phar file is on the bin folder as stated on the indicate instructions link.

**Comment by davidverholen** [comment]
ok, so you have something like this:

```json
{
    "require": {
        "magento-hackathon/magento-composer-installer": "*"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "packages.firegento.com"
        }
    ]
}
```

you could try to clear the composer cache (composer clearcache).
maybe it's still installed from there

**Comment by Flyingmana** [comment]
fixed by taking over and activate again the packagist entry
