### ISSUE TITLE
add a PHP dependency into the composer.json

### ISSUE THREAD

**Issue by lsmith77** [magento-hackathon/magento-composer-installer#150]
in an older project we were using 0.1.* and just found that 0.1.3 is using short array syntax which requires PHP 5.4.

in this spirit it would be good to at least add such a require now, so that in the future you can bump the require when the requirements increase to prevent surprising breakage for users.

**Comment by lsmith77** [comment]
ok ... in the end we wanted a 1.* release after all.
however it would still be good to add PHP depdenencies

**Comment by Flyingmana** [comment]
have added the version requirement in master(min 5.3.2 as composer itself has) and also added a 1.3.x branch.

Feel free to report cases where features are not compatible yet with 5.3
