### ISSUE TITLE
Fullstack tests do not cleanup after them selves

### ISSUE THREAD

**Issue by AydinHassan** [magento-hackathon/magento-composer-installer#171]
When I run the unit tests, the full stack tests do composer installs and leave loads of files hanging around, which messes up with my IDE file watching. This causing rescanning of folders which is pretty slow and makes my IDE unusable for ~2minutes. I also then get loads of complaints about duplicate classes.

Is it possible to clean up these directories in the `tearDown` method ?

If you point me in the right direction, I'll PR

**Comment by Flyingmana** [comment]
two possible solutions here.

1. exclude this directories in the IDE

2. put all this into a temporary directory outside


simpy clean up on tearDown will not be enough for many, as the IDE may notice the file changes earlier during the test run.


for 2. I planned to refactor the fullstack tests to use https://github.com/Cotya/composer-test-framework but thats a bigger task and not ready yet.

Would the possibility to exclude the directory be enough for you? At least for now.

**Comment by AydinHassan** [comment]
Yeah that's what I've done already. Number 2 sounds good, maybe we can also look at seperating the full stack stuff in to its own testsuite, so the simple unit tests can be run on their own, it's painfully slow to run the whole suite atm.
