### ISSUE TITLE
Having performance time problem with composer update

### ISSUE THREAD

**Issue by sergis** [magento-hackathon/magento-composer-installer#182]
Recently I've been encountering performance problem with composer update. Update time increased from 2-3 min to 40min. 
It  seems the reason is in big size magento/media/ folder (~10G) and composer going throughout whole folder even product/cache (confirmed by lsof monitoring) for a very long time.

Would you please explain what's up or what's wrong?

**Comment by Flyingmana** [comment]
what is your composer json, and what way did you use for the magento core part. Did you use the magento/core package? it has some special behavior to preserve the media folder.

**Comment by sergis** [comment]
"require": {
        "magento-hackathon/magento-composer-installer": "*",
        "ETWS/et_russianlanguagepack": "dev-master",
.......~25 our packages
          },
    "extra": {
        "magento-force": "override",
        "magento-deploystrategy" : "copy",
        "magento-root-dir": "./magento"
    }

**Comment by Flyingmana** [comment]
does this also happen with the `3.0.0-beta.1` release?
