### ISSUE TITLE
What is the state of this repository?

### ISSUE THREAD

**Issue by Narno** [magento-hackathon/magento-composer-installer#187]
The README says "Main Development now does happen at https://github.com/Cotya/magento-composer-installer". May be you should turn off / close the current repository for the benefit of "Cotya/magento-composer-installer"?

**Comment by Flyingmana** [comment]
This Repository does not belong to me, so this Decision is outside of my power.
But there are a lot of people who have hardcoded this Repository into their build process, composer.json, composer config.
Maybe there will come a time, but closing it now will break a lot of things without benefits.

Also there are still a lot of issue entries, which should first get resolved in some kind, to not cause confusion.

**Comment by nevvermind** [comment]
Yeah, but people are making PRs against an obsolete codebase, fixing stuff that may very well be already fixed in https://github.com/Cotya/magento-composer-installer

The readme of this repo should make it more obvious that's deprecated. Make it red or something.

**Comment by Flyingmana** [comment]
no colors for READMEs: https://stackoverflow.com/questions/11509830/how-to-add-color-to-githubs-readme-md-file

But it should be very clear I hope if someone actually reads it....

Maybe I should add a cleaning commit, to empty the content of the Branch Heads so noone tries to add PRs anymore, I will do something when I have enough time over, but it does not seem to be a big Issue to still have this repository.

**Comment by scottsb** [comment]
I think there's merit to what nevvermind says. The way GitHub works with forks of forks, it's awkward to do a pull request into the Cotya repo so long as this one is open. A pull request that you intend to go to Cotya can end up going here by accident. Clearing the branches would at least give a heads up that something is up, but closing the repo would be the best option.
