### ISSUE TITLE
Can't composer update with magento-deploystrategy:copy & magento-force=true

### ISSUE THREAD

**Issue by dmytrunets** [magento-hackathon/magento-composer-installer#189]
Problem: 
During composer update occur error files of package already exists.

Investigate:
param magento-force not set for deploy Strategy Object:
Method where injecting isForced setting from extra config
\MagentoHackathon\Composer\Magento\Installer\MagentoInstallerAbstract::getDeployStrategy
don't call.

magento-hackathon/magento-composer-installer = 3.0.0-alpha.2

**Comment by Flyingmana** [comment]
sorry for the late response.
if you use packages.firegento.com or packagist you should be able to use 3.0.2, does this error happen there too?

you may need to clean the destination first, or is there some package which tries to deploy identical files?

**Comment by dmytrunets** [comment]
Thanks,  in v3.0.2 this problem doesn't occur.

**Comment by Flyingmana** [comment]
you're welcome :)
