### ISSUE TITLE
No proper announcement of PHP version

### ISSUE THREAD

**Issue by tkn98** [magento-hackathon/magento-composer-installer#195]
**magento-hackathon/magento-composer-installer** as dependency in a PHP 5.3 environment get's fatal errors on parse  / syntax because of PHP 5.4 array notation (short arrays).

Example: https://travis-ci.org/firegento/firegento-magesetup/jobs/75237184

**Comment by Flyingmana** [comment]
was for later versions fixed by not allowing it to install in 5.3.
I could remove the tags where the new annotation is used without notice in the composer.json, but that may hit a few more.

**Comment by tkn98** [comment]
@Flyingmana: Thanks for the quick feedback. Well I got hit by that in a downstream project. Can you tell me what the last version with PHP 5.3 support was? That then would allow to pin it because the downstream project supports PHP 5.3 still according to their docs.

And yes, if your package needs PHP 5.4 to work, you should highlight that in the requirements in composer json: https://getcomposer.org/doc/02-libraries.md#platform-packages

It should hit those who are affected as early and fast as possible. Fail fast, fail early.

**Comment by Flyingmana** [comment]
you will have to test this by yourself.

Problem was, it was first noticed a lot later after introducing the 5.4 only features.

**Comment by tkn98** [comment]
So the last known good 5.3 version is more or less somewhere in the past? And it's not adviseable to use **magento-hackathon/magento-composer-installer** for projects that offer support for PHP 5.3?

Have you a related issue number so I can read up a bit about this? And sorry to beat a dead horse here, downstream has just no version constraint at all within their composer.json:

```
  "magento-hackathon/magento-composer-installer": "*"
```

So if I read your last comment right, it means the last known good revision with PHP 5.3 is unknown, correct?

**Comment by therouv** [comment]
@tkn98 I use version 2.1.1 for PHP 5.3 projects. Haven't tested more current versions yet.

**Comment by tkn98** [comment]
@therouv: Nice, thanks for the number. That's at least a known good :+1:

**Comment by Flyingmana** [comment]
exactly, its unknown.

related:  
- https://github.com/Cotya/magento-composer-installer/pull/44
- https://github.com/Cotya/magento-composer-installer/issues/43

I want to mention, that if someone is willing to pay for 5.3 support, I have no problem with guaranteeing support for it, even if it is outdated and noone should use it anymore ( for example last week there were 12 security fixes in php, which are not part of 5.3 )

**Comment by tkn98** [comment]
@Flyingmana: That's good news. I can't say which of our customers still have 5.3 implications but for those who have, this might be a viable option. So thanks for the offer.

**Comment by Flyingmana** [comment]
one and a half year later and nobody wanted to pay for keeping old versions. So I will close this topic for now
