### ISSUE TITLE
Deprecation Notice: The callback MagentoHackathon\Composer\Magento\Plugin::onPackageUpdate

### ISSUE THREAD

**Issue by mozgbrasil** [magento-hackathon/magento-composer-installer#196]
Hello

Good Morning

When I am performing an update via composer, this alert is now being displayed

Do you have any information to correct this error?

Deprecation Notice: The callback MagentoHackathon\Composer\Magento\Plugin::onPackageUpdate declared at /public_html/vendor/magento-hackathon/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Plugin.php accepts a Composer\Script\PackageEvent but pre-package-update events use a Composer\Installer\PackageEvent instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:317

![captura de tela de 2017-01-17 11-05-23](https://cloud.githubusercontent.com/assets/17202780/22021639/833e0e2a-dca5-11e6-8528-8c46cfa271f6.png)

**Comment by Flyingmana** [comment]
this will soon be fixed with a new bugfix release

**Comment by mozgbrasil** [comment]
Thank you my friend

**Comment by Flyingmana** [comment]
fixed in 3.1
https://github.com/Cotya/magento-composer-installer/issues/118
