### ISSUE TITLE
[ErrorException] Unable to find deploy strategy for module: no known mapping

### ISSUE THREAD

**Issue by yellowmamba** [magento-hackathon/magento-composer-installer#78]
Hi,

I am running into this problem when installing AW_blog extension. I want to manage this plugin myself, so I downloaded it as a zip from http://packages.firegento.com/. In the package, it contains a `package.xml` file, which should be found by the installer according to your readme file.But this error occurs, so symlink cannot be done. Here's the installing process:

```
-> composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing magento-hackathon/magento-composer-installer (1.3.1)
    Loading from cache

 time for voting about the future of the #magento #composer installer.
 https://github.com/magento-hackathon/magento-composer-installer/blob/discussion-master/Milestone/2/index.md
 For the case you don't vote, I will ignore your problems till iam finished with the resulting release.
  - Installing plugins/aw_blog (v1.3.1)
    Cloning 64019641e4c488237a11e6b36bf36ad1d4c21f69




  [ErrorException]
  Unable to find deploy strategy for module: no known mapping
```

Do you have any idea? Thanks!

**Comment by andkirby** [comment]
Hey guys,
is there any updates about modman file usage?..
I won't use package.xml.

**Comment by andkirby** [comment]
> as manually creating modman is really tedious
By the way, you may try use mine simple generator.
https://github.com/andkirby/modman-generator

**Comment by daim2k5** [comment]
why you don't use composer? @andkirby as @Flyingmana mention it's a edge case :-/

**Comment by andkirby** [comment]
Sorry, my fault - one of required modules didn't have modman file.
Composer for what? I use Composer. I'm using modman to make deploy mapping. Is this way wrong? :)

**Comment by Flyingmana** [comment]
@andkirby please open a new issue with some more details to reproduce.
The name of the package you want to install, the version of this package and the version of composer and the version of the magento composer installer you use.
